version: '3'

services:
  webapp1:
    build:
      context: ./app1
    ports:
      - "8001:5000"

  webapp2:
    build:
      context: ./app2
    ports:
      - "8002:5000"
      
  load_balancer:
    image: nginx:latest
    ports:
      - "80:8088"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./packets/:/home/packets/
    depends_on:
      - webapp1
      - webapp2
